name: Build, Test, and Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - examples/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - examples/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build -x test -x spotlessCheck

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            build/libs
            build/classes
          key: ${{ runner.os }}-build-${{ github.sha }}

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            build/libs
            build/classes
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run linters
        run: ./gradlew spotlessCheck

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            build/libs
            build/classes
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run tests
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/test-results/

  docker:
    needs: [lint, test]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            build/libs
            build/classes
          key: ${{ runner.os }}-build-${{ github.sha }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
